#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use wappr\Command\ResizeCommand;

$application = new Application();

$application->add(new ResizeCommand);

$application->run();
